// <auto-generated />
using System;
using Chenpess.QuickBuy.Repositorio.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Chenpess.QuickBuy.Repositorio.Migrations
{
    [DbContext(typeof(QuickBuyContexto))]
    partial class QuickBuyContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Chenpess.QuickBuy.Dominio.BLL.FormaPagamento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("FormaPagamento");
                });

            modelBuilder.Entity("Chenpess.QuickBuy.Dominio.Entidades.ItemPedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Pedidoid");

                    b.Property<int>("produtoId");

                    b.Property<int>("quantidade");

                    b.HasKey("id");

                    b.HasIndex("Pedidoid");

                    b.ToTable("ItemPedido");
                });

            modelBuilder.Entity("Chenpess.QuickBuy.Dominio.Entidades.Pedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("FormaPagamentoId");

                    b.Property<int>("UsuarioId");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("dataPedido");

                    b.Property<DateTime>("dataPrevisaoEntrega");

                    b.Property<string>("enderecoCompleto")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("numeroEndereco")
                        .IsRequired();

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.HasKey("id");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Chenpess.QuickBuy.Dominio.Entidades.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descricao");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<decimal>("preco");

                    b.Property<int>("quantidade");

                    b.HasKey("id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Chenpess.QuickBuy.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<string>("sobreNome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Chenpess.QuickBuy.Dominio.Entidades.ItemPedido", b =>
                {
                    b.HasOne("Chenpess.QuickBuy.Dominio.Entidades.Pedido")
                        .WithMany("itensPedido")
                        .HasForeignKey("Pedidoid");
                });

            modelBuilder.Entity("Chenpess.QuickBuy.Dominio.Entidades.Pedido", b =>
                {
                    b.HasOne("Chenpess.QuickBuy.Dominio.BLL.FormaPagamento", "formaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Chenpess.QuickBuy.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
